sudo: required

services:
  - docker

before_install:
  - docker build -t rajhaldar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajhaldar/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "docker"
  on:
    branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
